version: '3'
services:

  db:
    image: postgres:alpine
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    ports:
      - 16379:6379

  web:
    build: .
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql://postgres@db/postgres
      REDIS_URL: redis://redis
      SECRET_KEY: deadbeef
    ports:
      - 5000:80
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
